sudo: required
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
script:
- echo $REPO:$TAG
- docker build -t $REPO:$TAG .
- docker run --name $IMAGE -d $REPO:$TAG 
- docker ps -a
- sleep 5
- docker logs $IMAGE
- docker exec $IMAGE pgrep tinyproxy
after_script:
- docker rm -f $IMAGE
env:
  global:
  - IMAGE=tinyproxy
  - REPO=$DOCKER_HUB_USERNAME/$IMAGE
notifications:
  pushover:
    api_key:
      secure: CBScinrcwSS7nHzDz4m868WfCZLMwi5H5nc4+4tNSJ/mTL1VQ5O2V40uJ0xhoOhy2AmEs2bEnSP9GmcM0utX6JFqAizhYcQaVMk7t8Z/rXF17RkLCOWdZrVjMsPmvqdm/pxEN/rXnrWrvv0vnbyt0ywDe4AnI/IY8IaNzL15sH1ETLi0hpfarfCfBVpVlSGl01chPvBgwc4RsXfC/Bne8IQ5NomasTUDbxn8CO10rHa69G5S5T+Ky39lTvLpBB1NlcQ3RFom4OB60puERN8OZl3w9EVFCmy82b3ROiiHsZg9ymLCAbzCaygsv99LxjcWWlnL32DVXF0JD7b3t8D2Ny8Shi0T8HPnXzRUGJI9wTRvYx/qiJ/H8LArZC+QxHjxn1pjpGAw7MVtdr7MGrfL5atiQkhM7ST2AwF56q5cjl8EII8GTCc9gDfIOLRDheH3AJjom+Rh6fjsFu4QepX9hdhI+tvd1TVUM7mbBIMG8Kaxa6kpQzj2rTJD9cR9DJc8C98GDfE5VBRorFqj2Fy9Kd2XxlWAvpSOgRXRztyn6/t0cvfiN7gC6iHj1yXdbccDZO9ihYXrtOZKtX/Y6SwO2WkjsdD1Sxh7g2msT42Z2P6FuRFdeMYDua8trgN56F8hkh6klxrXbXx10Wf9jCjZi1ywKdBYPE0iiCPHt/tPFHM=
    users:
      secure: pJHRACbMPLa7sJkqpL1kNXlPwrCaPTNICSo/x5vFli3b2urLSPn7esaI0psuPFg3k492XRKBZ9/vYYUZGMKPCdw3OiIgegNz0mnsD2Dcn6aG5/8PoSq/LyXcdBEF1MSK7EcD3XYPKP9vCbCz/WjaDbxPYcLu4WjSJyuaAF0RA9igXMaMZkEBaxZY0e2xxz3cWWkXkF3rqw/+g+CcdWy/aEpCvOcS2vNdCzITMTkkWejeIjA5dGZuSdyEq8wVoCmfCli50z6ihpVbSG5UKBt7c8tmaGtb9erI076V3EkdF22ccEw4jjvOcFps3NCrSbMGVD8+bNLvA05qszeQOdd5sTuXnXFlY6NzXThfgA6jXUi8bfcp8HUsv0BJ+AAlz2u2+8Oj+297ZAzxGT2ECZegtgvZFWgpq5+5na8sQT7+XtS2oPXa6DvGkB9mCb1dX0jWr+JCIewZEUgzpYLcB4hvpDMdvefsPBKP6/a4K5iOo64WfuQ5nkBwLrNS97ymYmbvG1n4TdLmvFz7VboxKaPIR2okXbJnNacZCrXfH1XZyzUtBKf/qzHKdty8+TcDr9NQZ6qZ539/S8ODbDrQLFUPmX2XHvTAGhHRDdtZ+o8cdeKbTy3JKh+8TXFWrJPqZRL+DcVYmSxAIBoxb2G2lrfNKsJKG6eihxeJUtpqkT305vk=
